### PR TITLE
Improve packaging

### PR DESCRIPTION
**Pull request by agateau-gg**
This PR improves a few details of the generated archives and Linux packages:

- archives are now in their own directory
- Windows archives are zip files
- deb and rpm contains more metadata and include the README.md and LICENSE files

I also added a `dist` Makefile target to make it easier to work on packaging.

### CODE REVIEW

**Comment by pierrelalanne** [comment]
Cool, it looks good to me.  
Also, I think we could switch from `go-version: 1.16` to `go-version: 1.17` in `.github/workflows/tag.yaml`. This should be tested locally but should not cause any trouble. Yet, it will allow to support Windows ARM64 architecture. WDYT ?

**Review by pierrelalanne — CHANGES_REQUESTED** [review]
Cool, it looks good to me.  
Also, I think we could switch from `go-version: 1.16` to `go-version: 1.17` in `.github/workflows/tag.yaml`. This should not cause any trouble. Yet, it will allow to [support Windows ARM64 architecture](https://go.dev/doc/go1.17). WDYT ?

**Comment by agateau-gg** [comment]
> Cool, it looks good to me. Also, I think we could switch from `go-version: 1.16` to `go-version: 1.17` in `.github/workflows/tag.yaml`. This should not cause any trouble. Yet, it will allow to [support Windows ARM64 architecture](https://go.dev/doc/go1.17). WDYT ?

I don't know go, so I have no idea what problems changing the go version could cause. In any case it feels like a different topic than adjusting what is in the existing packages.

**Comment by pierrelalanne** [comment]
> I don't know go, so I have no idea what problems changing the go version could cause. In any case it feels like a different topic than adjusting what is in the existing packages.

Ok, this was to support an extra architecture, I will push it in a separate PR.

**Review by pierrelalanne — APPROVED** [review]

**Pull request merged**
